[package]
name = "rpi-gpio"
version = "0.1.0"
authors = [
	"Fusion Engineering <info@fusion.engineering>",
	"Maarten de Vries <maarten@de-vri.es>",
]
edition = "2018"
license = "BSD-2-Clause"
readme  = "README.md"

[dependencies]
nix = "0.13"
structopt = "0.2"
yansi = "0.5"
